export const DEFAULT_SETTINGS = {
  pageFontFamily: "Inter, sans-serif",
  pageBackground: "#f4f6f9",
  titleText: "Restock Alerts",
  titleSize: "28",
  titleColor: "#0f172a",
  titleWeight: "bold",
  subtitleSize: "14",
  subtitleColor: "#64748b",
  card1Bg: "#fffbeb",
  card1NumColor: "#d97706",
  card2Bg: "#eff6ff",
  card2NumColor: "#1d4ed8",
  card3Bg: "#f0fdf4",
  card3NumColor: "#16a34a",
  cardNumSize: "32",
  cardLabelSize: "13",
  cardLabelColor: "#64748b",
  cardBorderRadius: "16",
  sectionTitleSize: "18",
  sectionTitleColor: "#1e293b",
  productCardBg: "#ffffff",
  productCardBorderColor: "#e2e8f0",
  productCardBorderRadius: "14",
  productCardHeaderBg: "#f8fafc",
  accentColor: "#6366f1",
  waitingBadgeBg: "#fef9c3",
  waitingBadgeColor: "#854d0e",
  openBadgeColor: "#ffffff",
  tableHeaderBg: "#f8fafc",
  tableHeaderColor: "#64748b",
  tableRowEvenBg: "#ffffff",
  tableRowOddBg: "#f8fafc",
  tableFontSize: "14",
  tableTextColor: "#334155",
  statusBadgeBg: "#fef9c3",
  statusBadgeColor: "#854d0e",
  viewBtnBg: "#0f172a",
  viewBtnColor: "#ffffff",
  viewBtnBorderRadius: "8",
};

export const TABS = ["Page", "Title", "Cards", "Products", "Table", "Buttons"];
